apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: wasm
  name: wasm
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - image: docker.pkg.github.com/jbrejnholt/dotnet-wasm-console:v0.0.1 # didn't work in Mac with Rancher
    name: wasm
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
