apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: wasm
  name: wasm
spec:
  containers:
  - image: docker.io/jhested/docker-wasm:0.1
    name: wasm
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
